// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto

#ifndef PROTOBUF_INCLUDED_status_2eproto
#define PROTOBUF_INCLUDED_status_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_status_2eproto 

namespace protobuf_status_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_status_2eproto
namespace status {
class StatusUpdate;
class StatusUpdateDefaultTypeInternal;
extern StatusUpdateDefaultTypeInternal _StatusUpdate_default_instance_;
}  // namespace status
namespace google {
namespace protobuf {
template<> ::status::StatusUpdate* Arena::CreateMaybeMessage<::status::StatusUpdate>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace status {

// ===================================================================

class StatusUpdate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:status.StatusUpdate) */ {
 public:
  StatusUpdate();
  virtual ~StatusUpdate();

  StatusUpdate(const StatusUpdate& from);

  inline StatusUpdate& operator=(const StatusUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StatusUpdate(StatusUpdate&& from) noexcept
    : StatusUpdate() {
    *this = ::std::move(from);
  }

  inline StatusUpdate& operator=(StatusUpdate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusUpdate& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatusUpdate* internal_default_instance() {
    return reinterpret_cast<const StatusUpdate*>(
               &_StatusUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(StatusUpdate* other);
  friend void swap(StatusUpdate& a, StatusUpdate& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StatusUpdate* New() const final {
    return CreateMaybeMessage<StatusUpdate>(NULL);
  }

  StatusUpdate* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StatusUpdate>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StatusUpdate& from);
  void MergeFrom(const StatusUpdate& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusUpdate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string info = 1;
  void clear_info();
  static const int kInfoFieldNumber = 1;
  const ::std::string& info() const;
  void set_info(const ::std::string& value);
  #if LANG_CXX11
  void set_info(::std::string&& value);
  #endif
  void set_info(const char* value);
  void set_info(const char* value, size_t size);
  ::std::string* mutable_info();
  ::std::string* release_info();
  void set_allocated_info(::std::string* info);

  // float cpu = 2;
  void clear_cpu();
  static const int kCpuFieldNumber = 2;
  float cpu() const;
  void set_cpu(float value);

  // float mem = 3;
  void clear_mem();
  static const int kMemFieldNumber = 3;
  float mem() const;
  void set_mem(float value);

  // @@protoc_insertion_point(class_scope:status.StatusUpdate)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr info_;
  float cpu_;
  float mem_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_status_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StatusUpdate

// string info = 1;
inline void StatusUpdate::clear_info() {
  info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StatusUpdate::info() const {
  // @@protoc_insertion_point(field_get:status.StatusUpdate.info)
  return info_.GetNoArena();
}
inline void StatusUpdate::set_info(const ::std::string& value) {
  
  info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:status.StatusUpdate.info)
}
#if LANG_CXX11
inline void StatusUpdate::set_info(::std::string&& value) {
  
  info_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:status.StatusUpdate.info)
}
#endif
inline void StatusUpdate::set_info(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:status.StatusUpdate.info)
}
inline void StatusUpdate::set_info(const char* value, size_t size) {
  
  info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:status.StatusUpdate.info)
}
inline ::std::string* StatusUpdate::mutable_info() {
  
  // @@protoc_insertion_point(field_mutable:status.StatusUpdate.info)
  return info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StatusUpdate::release_info() {
  // @@protoc_insertion_point(field_release:status.StatusUpdate.info)
  
  return info_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StatusUpdate::set_allocated_info(::std::string* info) {
  if (info != NULL) {
    
  } else {
    
  }
  info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), info);
  // @@protoc_insertion_point(field_set_allocated:status.StatusUpdate.info)
}

// float cpu = 2;
inline void StatusUpdate::clear_cpu() {
  cpu_ = 0;
}
inline float StatusUpdate::cpu() const {
  // @@protoc_insertion_point(field_get:status.StatusUpdate.cpu)
  return cpu_;
}
inline void StatusUpdate::set_cpu(float value) {
  
  cpu_ = value;
  // @@protoc_insertion_point(field_set:status.StatusUpdate.cpu)
}

// float mem = 3;
inline void StatusUpdate::clear_mem() {
  mem_ = 0;
}
inline float StatusUpdate::mem() const {
  // @@protoc_insertion_point(field_get:status.StatusUpdate.mem)
  return mem_;
}
inline void StatusUpdate::set_mem(float value) {
  
  mem_ = value;
  // @@protoc_insertion_point(field_set:status.StatusUpdate.mem)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace status

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_status_2eproto
